# Generated by Django 3.0.4 on 2020-03-21 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(default='Mumbai', max_length=500)),
                ('No_of_donations', models.IntegerField(default=0)),
                ('DOB', models.CharField(default='i am default', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bloodbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blood_Bank_Name', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=500)),
                ('District', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=500)),
                ('Address', models.CharField(max_length=500)),
                ('Pincode', models.CharField(max_length=500)),
                ('Contact_No', models.CharField(max_length=500)),
                ('Mobile', models.CharField(max_length=500)),
                ('Helpline', models.CharField(max_length=500)),
                ('Fax', models.CharField(max_length=500)),
                ('Email', models.CharField(max_length=500)),
                ('Website', models.CharField(max_length=500)),
                ('Nodal_Officer', models.CharField(max_length=500)),
                ('Contact_Nodal_Officer', models.CharField(max_length=500)),
                ('Mobile_Nodal_Officer', models.CharField(max_length=500)),
                ('Email_Nodal_Officer', models.CharField(max_length=500)),
                ('Qualification_Nodal_Officer', models.CharField(max_length=500)),
                ('Category', models.CharField(max_length=500)),
                ('Blood_Component_Available', models.CharField(max_length=500)),
                ('Apheresis', models.CharField(max_length=500)),
                ('Service_Time', models.CharField(max_length=500)),
                ('License', models.CharField(max_length=500)),
                ('Date_License_Obtained', models.CharField(max_length=500)),
                ('Date_of_Renewal', models.CharField(max_length=500)),
                ('Latitude', models.CharField(max_length=500)),
                ('Longitude', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
