# Generated by Django 3.0.4 on 2020-03-21 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_bags', models.IntegerField()),
                ('Blood_component', models.CharField(max_length=5)),
                ('Blood_group', models.CharField(max_length=5)),
                ('Cost', models.IntegerField()),
                ('Bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Bloodbank')),
            ],
        ),
    ]
