# Generated by Django 3.0.4 on 2020-03-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20200321_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Blood_component',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Blood_group',
            field=models.CharField(max_length=50),
        ),
    ]
